sonar.projectKey=secure-notes-app
sonar.projectName=Secure Notes App
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

# Ignore build artifacts and dependencies
# sonar.exclusions=node_modules/**,dist/**,coverage/**


#sonar.sources=.

