sonar.projectKey=Secdo
sonar.projectName=SecDO-DVWA
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

# Optional exclusions
# sonar.exclusions=vendor/**,tests/**,.github/**,database/**
